name: Generate openAPI index

on:
  push:
    branches:
      - main

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate index.json
        run: |
          cd docs/openAPI
          ls *.yaml *.yml 2>/dev/null | jq -R -s -c 'split("\n")[:-1]' > ../urls/index.json

      - name: Commit and push changes
        env:
          PAT_TOKEN: ${{ secrets.PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add docs/urls/index.json
          git commit -m "Auto-generate openAPI index.json" || exit 0
          git push https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git main
